# Page information
site_name: SparkFun Thing Plus - ESP32 WROOM (USB-C) Hookup Guide
site_description: A hookup guide for the ESP32-WROOM Thing Plus (USB-C)
site_url: https://sparkfun.github.io/SparkFun_Thing_Plus_ESP32_WROOM_C
site_author: SparkFun Electronics

repo_url: https://github.com/sparkfun/SparkFun_Thing_Plus_ESP32_WROOM_C
repo_name: sparkfun/SparkFun_Thing_Plus_ESP32_WROOM_C

copyright: Copyright 2022 SparkFun Electronics (6333 Dry Creek Parkway, Niwot, Colorado 80503)

# Configuration for webpage theme
theme:
  # Theme: https://squidfunk.github.io/mkdocs-material/
  name: material

  # Header Logo
  logo: img/sfe_logo_sm.png
  # Page Font
  font:
    text: Roboto
    code: Roboto Mono
  
  # Features to Include (ref. theme docsumentation)
  features:
    - content.code.annotate
    # Enable "view source" and "edit this page" buttons
    - content.action.edit
    # - content.action.view

    - navigation.tracking
    - navigation.tabs.sticky
    - navigation.tabs    
  # Adds light/dark theme to webpage
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: grey
      accent: red
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: grey
      accent: red
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to system preference

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: grey
      accent: red
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode    

  # Configures icons of callout boxes
  icon:
    # Sets repo icon to GitHub icon
    repo: fontawesome/brands/github
    
    # Sets icons for "view source" (commented out) and "edit this page" buttons
    edit: material/file-document-edit-outline
    # view: material/file-code-outline


    # Admonition Icons
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: simple/sparkfun
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16
      # Add custom admonitions
      github: simple/github
      arduino: simple/arduino
      python: simple/python
      code: fontawesome/regular/file-code
      terminal: octicons/terminal-16
      serial: fontawesome/solid/display

  # Adds PDF icon to download hookup guide
  custom_dir: docs/overrides


# Included MkDocs plugins
# Add the installation of any new plugins to the ./github/workflows/mkdocs.yml file also
plugins:
  - search
  - monorepo
  # For PDF rendering
  # - with-pdf:
  #     cover_subtitle: none
  #     cover_logo: img/sfe_logo_sm.png
  #     exclude_pages: [ "single_page", "github/file_issue", "github/contribute" ]
  #     output_path: board_files/hookup_guide.pdf
  #     # debug_html: true


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.tilde
  - tables
  - admonition
  - md_in_html
  - attr_list

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/sparkfun
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/sparkfun
    - icon: fontawesome/brands/github
      link: https://www.github.com/sparkfun
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/SparkFun
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/sparkfun


# Configures styling for PDF rendering and webpage layout
extra_css:
  - overrides/extra.css


# Configures Page/Tab Navigation
nav:
  - Getting Started:
    - Introduction: index.md
    - Hardware Overview: hardware_overview.md
    - Hardware Assembly: hardware_assembly.md
    - Software Overview: software_overview.md
  - Resources: resources.md
    - Troubleshooting Tips: troubleshooting_tips.md
  - Issues/Pull Requests:
    - Issues: file_issue.md
    - Contribute: contribute.md