name: Run mkdocs
on:
  push:
    branches:
      - docs_test
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs-monorepo-plugin mkdocs-with-pdf mkdocs-git-authors-plugin mkdocs-git-revision-date-localized-plugin mkdocs-git-committers-plugin-2
      
      # - run: apt install pango1.0-tools
      - run: mkdocs gh-deploy --force
