name: Run mkdocs
on:
  push:
    branches:
      - docs_test
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python runtime
        uses: actions/setup-python@v4
        with:
          python-version: 3.x
      
      - name: Install Python dependencies
        run: pip install mkdocs-material mkdocs-monorepo-plugin mkdocs-with-pdf mkdocs-git-authors-plugin mkdocs-git-revision-date-localized-plugin mkdocs-git-committers-plugin-2

      - name: Install Insiders build
        if: github.event.repository.fork == false
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git clone --depth 1 https://${GH_TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
          pip install -e mkdocs-material-insiders
          cp mkdocs-material-insiders/mkdocs.yml mkdocs.yml
          echo "THEME_DIR=mkdocs-material-insiders/material" >> $GITHUB_ENV
      
      - name: Deploy documentation
        run: |
          mkdocs gh-deploy --force
          mkdocs --version